---
title: "Math Lab"
author: "Andrew Chen"
date: "7/7/2018"
output: html_document
---

```{r}
library(dplyr)
library(magrittr)
library(ggplot2)
```

###Cleaning Data
```{r}
lcd_data = read.csv('~/Desktop/Research/Extension_1.18.18_deidentified.csv', stringsAsFactors = FALSE)
comparisons = lcd_data %>% filter(random != 5089 & random != 9502 & random != 6531) %>% select(c(7:206, 397)) %>% slice(3:99)

for (i in 1:200) {
  comparisons[, i] = as.integer(unlist(comparisons[, i]))
}

comparisons = comparisons %>% filter(attcheck1_1 > 90 & attcheck3_1 > 90 & attcheck5_1 > 90 & attcheck7_1 > 90 & attcheck9_1 > 90)

comparisons = comparisons[-c(21,42,63,84,100,121,142,163,184,200)]
```

###Generating vectors of compared numbers
```{r}
numbers = c(5,14,16,9,29,8,11,20,18,21)
numbers2 = c(7,25,12,17,28,6,13,4,27,10)
num_mat = matrix(0,10,10)
for (i in 1:10) {
  num_mat[i,] = numbers
  numbers = numbers[c(2:10, 1)]
}

for (j in 1:10) {
  num_mat = cbind(num_mat, numbers2)
  numbers2 = numbers2[c(2:10,1)]
}

colnames(num_mat) = rep(NULL, 20)
```

###Generating vectors of compared fields
```{r}
field1 <- c(rep(1, 10), rep(c(1, 11), 5))
field2 <- c(2,16,3,17,4,18,5,19,6,20,11,rep(12:15, each = 2), 16)
```

###Changing columns into numbers that are compared
```{r}
x = 0
f1 = 1
f2 = 1
while (i + x <= 190) {
  if (x == 80 | x == 185) {
    for (i in 1:5) {
    colnames(comparisons)[i + x] = paste0(num_mat[i, field1[f1]], "/", num_mat[i, field2[f2]])
    }
    f1 = f1 + 1
    f2 = f2 + 1
    x = x + 5
    next
  } else {
    for (i in 1:10) {
    colnames(comparisons)[i + x] = paste0(num_mat[i, field1[f1]], "/", num_mat[i, field2[f2]])
    }
  }
  x = x + 10
  f1 = f1 + 1
  f2 = f2 + 1
  i = 5
}
```

###Creating Table of Demographics and Scores
```{r}
demo = lcd_data %>% slice(3:102) %>% filter(random != 5089 & random != 9502 & random != 6531)

for (i in 1:200) {
  demo[, i] = as.integer(unlist(demo[, i]))
}

demo = demo %>% filter(attcheck1_1 > 90 & attcheck3_1 > 90 & attcheck5_1 > 90 & attcheck7_1 > 90 & attcheck9_1 > 90) %>% select(367:395)

demo[, c(1,2,14:29)] = as.integer(unlist(demo[, c(1,2,14:29)]))

colnames(demo)[1] = "anxiety"
colnames(demo)[14:21] = paste0("r", 0:7)
colnames(demo)[22:29] = paste0("w", 0:7)

demo = demo %>% mutate(score = r0+r1+r2+r3+r4+r5+r6+r7-w0-w1-w2-w3-w4-w5-w6-w7)
```

###Attempt at Regression Analysis
```{r}
score_vs_anxiety = lm(demo$score ~ demo$anxiety)
summary(score_vs_anxiety)

score_vs_age = lm(demo$score ~ demo$age, demo)
summary(score_vs_age)

ggplot(demo, aes(x = age, y = score)) + geom_point(col = "red", size = 2, alpha = .5) + geom_smooth(method = lm)

ggplot(demo, aes(x = anxiety, y = score)) + geom_point(col = "red", size = 2, alpha = .5) + geom_smooth(method = lm)
```

###analysisssssssss
```{r}
ggplot(demo, aes(score)) + geom_histogram(fill = "green", alpha = .5, breaks = seq(0, 50, 5)) + scale_x_continuous(limits = c(20, 50), breaks = seq(0,50,5))
mean(demo$score)
median(demo$score)
sd(demo$score)
```

```{r}
hist(demo$anxiety)
ggplot(demo, aes(anxiety)) + geom_histogram(fill = "green", alpha = .5, binwidth = 1) +
  scale_x_continuous(breaks = seq(0,10,1))
mean(demo$anxiety)
median(demo$anxiety)
sd(demo$anxiety)
```

```{r}
gen_count = demo %>% count(gender)
eth_count = demo %>% count(ethnicity)
math_count = demo %>% count(math_freq)
sem_count = demo %>% count(college_semesters)
pro_count = demo %>% count(profession)
anx_count = demo %>% count(anxiety)
```

```{r}
demo %>% group_by(gender) %>% summarise(mean = mean(score)) %>% mutate(freq = gen_count$n) %>% arrange(desc(mean)) 
demo %>% group_by(ethnicity) %>% summarise(mean = mean(score)) %>% mutate(freq = eth_count$n) %>% arrange(desc(mean)) 
demo %>% group_by(college_semesters) %>% summarise(mean = mean(score)) %>% mutate(freq = sem_count$n)
demo %>% group_by(math_freq) %>% summarise(mean = mean(score)) %>% mutate(freq = math_count$n) %>% arrange(desc(mean)) 
demo %>% group_by(profession) %>% summarise(mean = mean(score)) %>% mutate(freq = pro_count$n) %>% arrange(desc(mean)) 
demo %>% group_by(anxiety) %>% summarise(mean = mean(score)) %>% mutate(freq = anx_count$n)
```

```{r}
#Mean scores of age groups
c1 = cut(demo$age, breaks = seq(20, 70, by = 10), include.lowest = T)
tapply(demo$score, c1, mean)
```

```{r}
lcd_data_w = read.csv('sim_data_with_weights.csv')
weights = lcd_data_w[,438:459]
```

```{r}
small_lm = lm(weights$small1 ~ weights$small2)
summary(small_lm)
ggplot(weights, aes(small1, y = small2)) + geom_point(col = "red", size = 2, alpha = .5) + geom_smooth(method = lm)
```

```{r}
med_lm = lm(weights$med1 ~ weights$med2)
ggplot(weights, aes(med1, y = med2)) + geom_point(col = "red", size = 2, alpha = .5) + geom_smooth(method = lm)
summary(med_lm)
```

```{r}
large_lm = lm(weights$large1 ~ weights$large2)
ggplot(weights, aes(large1, y = large2)) + geom_point(col = "red", size = 2, alpha = .5) + geom_smooth(method = lm)
summary(large_lm)
```

```{r}
even_lm = lm(weights$even1 ~ weights$even2)
ggplot(weights, aes(even1, y = even2)) + geom_point(col = "red", size = 2, alpha = .5) + geom_smooth(method = lm)
summary(even_lm)
```

```{r}
odd_lm = lm(weights$odd1 ~ weights$odd2)
ggplot(weights, aes(odd1, odd2)) + geom_point(col = "red", size = 2, alpha = .5) + geom_smooth(method = lm)
summary(odd_lm)
```

```{r}
mult3_lm = lm(weights$mult31 ~ weights$mult32)
ggplot(weights, aes(mult31, mult32)) + geom_point(col = "red", size = 2, alpha = .5) + geom_smooth(method = lm)
summary(mult3_lm)
```

```{r}
mult4_lm = lm(weights$mult41 ~ weights$mult42)
ggplot(weights, aes(mult41, mult42)) + geom_point(col = "red", size = 2, alpha = .5) + geom_smooth(method = lm)
summary(mult4_lm)
```

```{r}
mult5_lm = lm(weights$mult51 ~ weights$mult52)
ggplot(weights, aes(mult51, mult52)) + geom_point(col = "red", size = 2, alpha = .5) + geom_smooth(method = lm)
summary(mult5_lm)
```

```{r}
mult7_lm = lm(weights$mult71 ~ weights$mult72)
ggplot(weights, aes(mult71, y = mult72)) + geom_point(col = "red", size = 2, alpha = .5) + geom_smooth(method = lm)
summary(mult7_lm)
```

```{r}
square_lm = lm(weights$square1 ~ weights$square2)
ggplot(weights, aes(square1, square2)) + geom_point(col = "red", size = 2, alpha = .5) + geom_smooth(method = lm)
summary(square_lm)
```

```{r}
prime_lm = lm(weights$prime1 ~ weights$prime2)
ggplot(weights, aes(prime1, y = prime2)) + geom_point(col = "red", size = 2, alpha = .5) + geom_smooth(method = lm)
summary(prime_lm)
```

```{r}
avgs = c()
for (i in 1:22) {
  avgs[i] = mean(weights[,i])
  names(avgs)[i] = names(weights)[i]
}
avgs
```

```{r}
r_squared = c(summary(small_lm)$r.squared,
              summary(med_lm)$r.squared,
              summary(large_lm)$r.squared,
              summary(even_lm)$r.squared,
              summary(odd_lm)$r.squared,
              summary(mult3_lm)$r.squared,
              summary(mult4_lm)$r.squared,
              summary(mult5_lm)$r.squared,
              summary(mult7_lm)$r.squared,
              summary(square_lm)$r.squared,
              summary(prime_lm)$r.squared)
names(r_squared) = c('small', 'med', 'large', 'even', 'odd', 'mult3', 'mult4', 'mult5', 'mult7', 'square', 'prime')
sort(r_squared, decreasing = T)
```

```{r}
avg_avgs = c()
for (i in 1:11) {
  avg_avgs[i] = mean(c(avgs[2*i - 1], avgs[2*i]))
  names(avg_avgs)[i] = names(r_squared)[i]
}

sort(avg_avgs, decreasing = T)
```

```{r}
ggplot(weights, aes(small1, resid(small_lm))) + geom_point(col = "red", alpha = .5, size = 2) + geom_hline(yintercept = 0)

ggplot(weights, aes(med1, resid(med_lm))) + geom_point(col = "red", alpha = .5, size = 2) + geom_hline(yintercept = 0)

ggplot(weights, aes(large1, resid(large_lm))) + geom_point(col = "red", alpha = .5, size = 2) + geom_hline(yintercept = 0)

ggplot(weights, aes(even1, resid(even_lm))) + geom_point(col = "red", alpha = .5, size = 2) + geom_hline(yintercept = 0)

ggplot(weights, aes(odd1, resid(odd_lm))) + geom_point(col = "red", alpha = .5, size = 2) + geom_hline(yintercept = 0)

ggplot(weights, aes(mult31, resid(mult3_lm))) + geom_point(col = "red", alpha = .5, size = 2) + geom_hline(yintercept = 0)

ggplot(weights, aes(mult41, resid(mult4_lm))) + geom_point(col = "red", alpha = .5, size = 2) + geom_hline(yintercept = 0)

ggplot(weights, aes(mult51, resid(mult5_lm))) + geom_point(col = "red", alpha = .5, size = 2) + geom_hline(yintercept = 0)

ggplot(weights, aes(mult71, resid(mult7_lm))) + geom_point(col = "red", alpha = .5, size = 2) + geom_hline(yintercept = 0)
```

```{r}
ggplot(small_lm) + geom_point(aes(x = .fitted, y = .resid), size = 2, col = "blue", alpha = .5) + geom_hline(yintercept = 0)

ggplot(med_lm) + geom_point(aes(x = .fitted, y = .resid), size = 2, col = "blue", alpha = .5) + geom_hline(yintercept = 0)

ggplot(large_lm) + geom_point(aes(x = .fitted, y = .resid), size = 2, col = "blue", alpha = .5) + geom_hline(yintercept = 0)

ggplot(even_lm) + geom_point(aes(x = .fitted, y = .resid), size = 2, col = "blue", alpha = .5) + geom_hline(yintercept = 0)

ggplot(odd_lm) + geom_point(aes(x = .fitted, y = .resid), size = 2, col = "blue", alpha = .5) + geom_hline(yintercept = 0)

ggplot(mult3_lm) + geom_point(aes(x = .fitted, y = .resid), size = 2, col = "blue", alpha = .5) + geom_hline(yintercept = 0)

ggplot(mult4_lm) + geom_point(aes(x = .fitted, y = .resid),  size = 2,col = "blue", alpha = .5) + geom_hline(yintercept = 0)

ggplot(mult5_lm) + geom_point(aes(x = .fitted, y = .resid), size = 2, col = "blue", alpha = .5) + geom_hline(yintercept = 0)

ggplot(mult7_lm) + geom_point(aes(x = .fitted, y = .resid), size = 2, col = "blue", alpha = .5) + geom_hline(yintercept = 0)

ggplot(square_lm) + geom_point(aes(x = .fitted, y = .resid), size = 2, col = "blue", alpha = .5) + geom_hline(yintercept = 0)

ggplot(prime_lm) + geom_point(aes(x = .fitted, y = .resid), size = 2, col = "blue", alpha = .5) + geom_hline(yintercept = 0)
```


```{r}
ggplot(weights, aes(sample = rstandard(small_lm))) + geom_qq(col = "purple", alpha = .5, size = 2) + geom_abline(intercept = 0, slope = 1)

ggplot(weights, aes(sample = rstandard(med_lm))) + geom_qq(col = "purple", alpha = .5, size = 2) + geom_abline(intercept = 0, slope = 1)

ggplot(weights, aes(sample = rstandard(large_lm))) + geom_qq(col = "purple", alpha = .5, size = 2) + geom_abline(intercept = 0, slope = 1)

ggplot(weights, aes(sample = rstandard(even_lm))) + geom_qq(col = "purple", alpha = .5, size = 2) + geom_abline(intercept = 0, slope = 1)

ggplot(weights, aes(sample = rstandard(odd_lm))) + geom_qq(col = "purple", alpha = .5, size = 2) + geom_abline(intercept = 0, slope = 1)

ggplot(weights, aes(sample = rstandard(mult3_lm))) + geom_qq(col = "purple", alpha = .5, size = 2) + geom_abline(intercept = 0, slope = 1)

ggplot(weights, aes(sample = rstandard(mult4_lm))) + geom_qq(col = "purple", alpha = .5, size = 2) + geom_abline(intercept = 0, slope = 1)

ggplot(weights, aes(sample = rstandard(mult5_lm))) + geom_qq(col = "purple", alpha = .5, size = 2) + geom_abline(intercept = 0, slope = 1)

ggplot(weights, aes(sample = rstandard(mult7_lm))) + geom_qq(col = "purple", alpha = .5, size = 2) + geom_abline(intercept = 0, slope = 1)

ggplot(weights, aes(sample = rstandard(square_lm))) + geom_qq(col = "purple", alpha = .5, size = 2) + geom_abline(intercept = 0, slope = 1)

ggplot(weights, aes(sample = rstandard(prime_lm))) + geom_qq(col = "purple", alpha = .5, size = 2) + geom_abline(intercept = 0, slope = 1)
```

###Creating Table
```{r}
comp = data.frame(simrating = integer(),
                  I = integer(),
                  J = integer(),
                  I_measure = character(),
                  J_measure = character(),
                  ID = integer(),
                  stringsAsFactors = F)
for (i in 1:84) {
  part = comparisons[i, ]
  for (j in 1:190) {
    sim = as.integer(part[, j])
    nums = as.integer(unlist(strsplit(colnames(part)[j], "/")))
    lst = list()
    lst[[1]] = sim
    lst[[2]] = nums[1]
    lst[[3]] = nums[2]
    lst[[4]] = ifelse(is.element(nums[1], numbers), "A", "B")
    lst[[5]] = ifelse(is.element(nums[2], numbers), "A", "B")
    lst[[6]] = as.integer(part[, 191])
    comp[190 * (i-1)+j, ] = lst
  }
}
```

###Converting Table to CSV
```{r}
write.csv(comp, file = '~/Desktop/Research/Comparisons.csv', row.names = F)
```
